### ISSUE TITLE
Dilithium imports missing

### ISSUE THREAD

**Issue by ramsdell** [GaloisInc/cryptol-specs#41] opened 2021-12-07 16:11 UTC
: At root of cryptol-specs
$ cryptol Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumRecommended.cry 
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.12.0
https://cryptol.net  :? for help

Loading module Cryptol
Loading module Primitive::Keyless::Hash::keccak
Loading module Common::utils
Loading module Common::bv
Loading module Common::mod_arith
Loading module Primitive::Asymmetric::Signature::Dilithium::test::test_latest
Loading module Primitive::Asymmetric::Signature::Dilithium::Round2::DilithiumParameterized
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:458:27--458:40
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:458:58--458:72
    Value not in scope: SHA3::SHAKE128
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:458:80--458:93
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:476:22--476:35
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:476:50--476:64
    Value not in scope: SHA3::SHAKE256
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:476:72--476:85
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:504:30--504:43
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:504:61--504:75
    Value not in scope: SHA3::SHAKE256
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:504:83--504:96
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:518:18--518:31
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:518:52--518:66
    Value not in scope: SHA3::SHAKE256
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:518:74--518:87
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:528:34--528:47
    Value not in scope: SHA3::toBytes
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:528:62--528:76
    Value not in scope: SHA3::SHAKE128
[error] at /Users/ramsdell/rep/cryptol-specs/Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumParameterized.cry:528:84--528:97
    Value not in scope: SHA3::toBytes
Loading module Cryptol
Cryptol>

**Comment by RyanGlScott** [comment] 2021-12-07 18:49
I'm fairly sure that is due to a recent refactoring in d15c5d035266b6b68db44ff67a332885ff25be3d. That commit moved some definitions out of `Primitive::Keyless::Hash::keccak`, but `DilithiumRecommended.cry` appears not to have been updated in the process.

**Comment by ajayeeralla** [comment] 2021-12-14 01:11
But I can compile without errors the version on the `master` branch though. I'm wondering which branch were you compiling?

**Comment by pnwamk** [comment] 2021-12-14 01:54
I can reproduce the issues on a fresh master:HEAD with Cryptol 2.12.0 (specifically 3371266ed6dc614eeac1706d82e0caf6c67a9975 of this repository); I believe these issues should be fixed when we merge this PR: https://github.com/GaloisInc/cryptol-specs/pull/43

**Comment by mccleeary-galois** [comment] 2024-08-29 14:13
We need to ensure this is still relevant and still a bug.

**Comment by marsella** [comment] 2024-10-01 18:53
This loads fine for me.

**Comment by mccleeary-galois** [comment] 2024-10-01 20:18
> cryptol Primitive/Asymmetric/Signature/Dilithium/Round2/DilithiumRecommended.cry

This appears to no longer be an issue. Closing.

**Closed by mccleeary-galois** 2024-10-01 20:18 UTC
Labels: bug
