### ISSUE TITLE
Remove coerceSize from MLKEM

### ISSUE THREAD

**Issue by rod-chapman** [GaloisInc/cryptol-specs#126] opened 2024-08-28 08:05 UTC
Following resolution of Issue #1489 and the release of Cryptol 3.2.0, the use of coerceSize in ML-KEM/specification.cry is no longer needed and can be removed.

**Comment by mccleeary-galois** [comment] 2024-08-29 14:22
This is probably a duplicate of #101, but we should ensure that both PRs open are indeed covering all of the uses of `coerce-size`

**Comment by rod-chapman** [comment] 2024-08-29 14:34
Actually.. I already opened PR #127 didn't I...

**Comment by mccleeary-galois** [comment] 2024-08-29 14:37
> Actually.. I already opened PR #127 didn't I...

No worries, I was more implying we should just ensure that all of the changes in #127 are captured in #107 or vice versa.

**Comment by rod-chapman** [comment] 2024-08-29 14:40
OK. I guess you could merge my commits, then merge those over to whatever branch is being used for #107. Please go ahead.

**Comment by marsella** [comment] 2024-10-11 14:03
This was closed by #107.

**Closed by marsella** 2024-10-11 14:03 UTC
Labels: good first issue, CNSA 2.0, improvement
